springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true


spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgres:5432/desafio
    # url: jdbc:postgresql://localhost:5432/desafio
    username: tenpo
    password: tenpo

server:
  error:
    include-message: always