springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true


spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: tenpo
    password: tenpo


#management.endpoint.auditevents.enabled: true