version: '3.1'
services:
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: tenpo
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      # To keep data between restarts uncomment the next line
      # - ./postgres-data:/var/lib/postgresql/data

  liquibase-update:
    image: liquibase/liquibase:3.10.x
    depends_on:
      - postgres
    working_dir: /db
    volumes:
        - ./db:/db
    command: --username=tenpo --password=tenpo --url=jdbc:postgresql://postgres/desafio --changeLogFile=changelog.xml update

  application:
    build: ../
    container_name: application
    ports:
      - 8080:8080
    depends_on:
      - liquibase-update
